// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Thermostat

#include "../ui.h"

void ui_MatterConfig_screen_init(void)
{
    ui_MatterConfig = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MatterConfig, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_scrollbar_mode(ui_MatterConfig, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_MatterConfig, lv_color_hex(0xB787E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MatterConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_MatterConfig, lv_color_hex(0xBE5757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_MatterConfig, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QrHomeBtn = lv_btn_create(ui_MatterConfig);
    lv_obj_set_width(ui_QrHomeBtn, 100);
    lv_obj_set_height(ui_QrHomeBtn, 36);
    lv_obj_set_x(ui_QrHomeBtn, -2);
    lv_obj_set_y(ui_QrHomeBtn, -3);
    lv_obj_set_align(ui_QrHomeBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_QrHomeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_QrHomeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_QrHomeBtn, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_QrHomeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_QrHomeBtn, lv_color_hex(0x2620F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_QrHomeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupHomeLabel1 = lv_label_create(ui_MatterConfig);
    lv_obj_set_width(ui_SetupHomeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetupHomeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetupHomeLabel1, -30);
    lv_obj_set_y(ui_SetupHomeLabel1, -14);
    lv_obj_set_align(ui_SetupHomeLabel1, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_SetupHomeLabel1, "Home");
    lv_obj_set_style_text_color(ui_SetupHomeLabel1, lv_color_hex(0xFFE300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetupHomeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_QRImage = lv_obj_create(ui_MatterConfig);
    lv_obj_set_width(ui_QRImage, 150);
    lv_obj_set_height(ui_QRImage, 150);
    lv_obj_set_x(ui_QRImage, 0);
    lv_obj_set_y(ui_QRImage, -20);
    lv_obj_set_align(ui_QRImage, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_QRImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_opa(ui_QRImage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ManualPairingCode = lv_label_create(ui_MatterConfig);
    lv_obj_set_width(ui_ManualPairingCode, 195);
    lv_obj_set_height(ui_ManualPairingCode, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ManualPairingCode, 13);
    lv_obj_set_y(ui_ManualPairingCode, -10);
    lv_obj_set_align(ui_ManualPairingCode, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_ManualPairingCode, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ManualPairingCode, "Manual Pairing Code");
    lv_obj_set_style_text_font(ui_ManualPairingCode, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_QrHomeBtn, ui_event_QrHomeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MatterConfig, ui_event_MatterConfig, LV_EVENT_ALL, NULL);

}
