// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Thermostat

#include "../ui.h"

void ui_Setup_screen_init(void)
{
    ui_Setup = lv_obj_create(NULL);
    lv_obj_add_state(ui_Setup, LV_STATE_USER_1);       /// States
    lv_obj_clear_flag(ui_Setup, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Setup, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Setup, lv_color_hex(0xB787E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setup, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Setup, lv_color_hex(0xBE5757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Setup, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempUnitsLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_TempUnitsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempUnitsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempUnitsLabel, 7);
    lv_obj_set_y(ui_TempUnitsLabel, -15);
    lv_obj_set_align(ui_TempUnitsLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TempUnitsLabel, "Temp Units: ");

    ui_FahrenheitLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_FahrenheitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FahrenheitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FahrenheitLabel, 133);
    lv_obj_set_y(ui_FahrenheitLabel, -15);
    lv_obj_set_align(ui_FahrenheitLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FahrenheitLabel, "F");

    ui_TempUnitsSwitch = lv_switch_create(ui_Setup);
    lv_obj_set_width(ui_TempUnitsSwitch, 50);
    lv_obj_set_height(ui_TempUnitsSwitch, 22);
    lv_obj_set_x(ui_TempUnitsSwitch, 13);
    lv_obj_set_y(ui_TempUnitsSwitch, -15);
    lv_obj_set_align(ui_TempUnitsSwitch, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_TempUnitsSwitch, LV_STATE_CHECKED);       /// States
    lv_obj_set_style_bg_color(ui_TempUnitsSwitch, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempUnitsSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CelciusLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_CelciusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CelciusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CelciusLabel, 203);
    lv_obj_set_y(ui_CelciusLabel, -15);
    lv_obj_set_align(ui_CelciusLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CelciusLabel, "C");

    ui_TempCorrectionTextLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_TempCorrectionTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCorrectionTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCorrectionTextLabel, 7);
    lv_obj_set_y(ui_TempCorrectionTextLabel, -100);
    lv_obj_set_align(ui_TempCorrectionTextLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TempCorrectionTextLabel, "Temp Correction:");

    ui_TempCorrectionLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_TempCorrectionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempCorrectionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempCorrectionLabel, 138);
    lv_obj_set_y(ui_TempCorrectionLabel, -100);
    lv_obj_set_align(ui_TempCorrectionLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TempCorrectionLabel, "-3.8°");

    ui_TempCorrectionSlider = lv_slider_create(ui_Setup);
    lv_slider_set_range(ui_TempCorrectionSlider, -65, 10);
    if(lv_slider_get_mode(ui_TempCorrectionSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_TempCorrectionSlider, -65, LV_ANIM_OFF);
    lv_obj_set_width(ui_TempCorrectionSlider, 127);
    lv_obj_set_height(ui_TempCorrectionSlider, 10);
    lv_obj_set_x(ui_TempCorrectionSlider, -9);
    lv_obj_set_y(ui_TempCorrectionSlider, -100);
    lv_obj_set_align(ui_TempCorrectionSlider, LV_ALIGN_RIGHT_MID);

    ui_TempSwingTextLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_TempSwingTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempSwingTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempSwingTextLabel, 7);
    lv_obj_set_y(ui_TempSwingTextLabel, -58);
    lv_obj_set_align(ui_TempSwingTextLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TempSwingTextLabel, "Temp Swing:");

    ui_TempSwingLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_TempSwingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempSwingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempSwingLabel, 138);
    lv_obj_set_y(ui_TempSwingLabel, -58);
    lv_obj_set_align(ui_TempSwingLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TempSwingLabel, "3.5°");

    ui_TempSwingSlider = lv_slider_create(ui_Setup);
    lv_slider_set_range(ui_TempSwingSlider, 0, 60);
    lv_slider_set_value(ui_TempSwingSlider, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_TempSwingSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_TempSwingSlider, 0,
                                                                                                    LV_ANIM_OFF);
    lv_obj_set_width(ui_TempSwingSlider, 127);
    lv_obj_set_height(ui_TempSwingSlider, 10);
    lv_obj_set_x(ui_TempSwingSlider, -9);
    lv_obj_set_y(ui_TempSwingSlider, -58);
    lv_obj_set_align(ui_TempSwingSlider, LV_ALIGN_RIGHT_MID);

    ui_HvacCoolLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_HvacCoolLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HvacCoolLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HvacCoolLabel, 7);
    lv_obj_set_y(ui_HvacCoolLabel, 31);
    lv_obj_set_align(ui_HvacCoolLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HvacCoolLabel, "HVAC Cool:");

    ui_HvacCoolCheckbox = lv_checkbox_create(ui_Setup);
    lv_checkbox_set_text(ui_HvacCoolCheckbox, "");
    lv_obj_set_width(ui_HvacCoolCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HvacCoolCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HvacCoolCheckbox, 0);
    lv_obj_set_y(ui_HvacCoolCheckbox, 31);
    lv_obj_set_align(ui_HvacCoolCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HvacCoolCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_HvacFanLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_HvacFanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HvacFanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HvacFanLabel, 7);
    lv_obj_set_y(ui_HvacFanLabel, 63);
    lv_obj_set_align(ui_HvacFanLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_HvacFanLabel, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_HvacFanLabel, "HVAC Fan:");

    ui_HvacFanCheckbox = lv_checkbox_create(ui_Setup);
    lv_checkbox_set_text(ui_HvacFanCheckbox, "");
    lv_obj_set_width(ui_HvacFanCheckbox, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HvacFanCheckbox, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HvacFanCheckbox, 0);
    lv_obj_set_y(ui_HvacFanCheckbox, 63);
    lv_obj_set_align(ui_HvacFanCheckbox, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HvacFanCheckbox, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_RevValveLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_RevValveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RevValveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RevValveLabel, 7);
    lv_obj_set_y(ui_RevValveLabel, 95);
    lv_obj_set_align(ui_RevValveLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_RevValveLabel, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_RevValveLabel, "********");

    ui_DisabledCheckbox3 = lv_checkbox_create(ui_Setup);
    lv_checkbox_set_text(ui_DisabledCheckbox3, "");
    lv_obj_set_width(ui_DisabledCheckbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DisabledCheckbox3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DisabledCheckbox3, 0);
    lv_obj_set_y(ui_DisabledCheckbox3, 95);
    lv_obj_set_align(ui_DisabledCheckbox3, LV_ALIGN_CENTER);
    lv_obj_add_state(ui_DisabledCheckbox3, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_DisabledCheckbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_SetupUncommonBtn = lv_btn_create(ui_Setup);
    lv_obj_set_width(ui_SetupUncommonBtn, 100);
    lv_obj_set_height(ui_SetupUncommonBtn, 36);
    lv_obj_set_x(ui_SetupUncommonBtn, -2);
    lv_obj_set_y(ui_SetupUncommonBtn, -45);
    lv_obj_set_align(ui_SetupUncommonBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_SetupUncommonBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetupUncommonBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetupUncommonBtn, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetupUncommonBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SetupUncommonBtn, lv_color_hex(0x2620F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SetupUncommonBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupUncommonLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_SetupUncommonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetupUncommonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetupUncommonLabel, -21);
    lv_obj_set_y(ui_SetupUncommonLabel, -56);
    lv_obj_set_align(ui_SetupUncommonLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_SetupUncommonLabel, "Unusual");
    lv_obj_set_style_text_color(ui_SetupUncommonLabel, lv_color_hex(0xFFE300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetupUncommonLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupHomeBtn = lv_btn_create(ui_Setup);
    lv_obj_set_width(ui_SetupHomeBtn, 100);
    lv_obj_set_height(ui_SetupHomeBtn, 36);
    lv_obj_set_x(ui_SetupHomeBtn, -2);
    lv_obj_set_y(ui_SetupHomeBtn, -3);
    lv_obj_set_align(ui_SetupHomeBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_SetupHomeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SetupHomeBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetupHomeBtn, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetupHomeBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SetupHomeBtn, lv_color_hex(0x2620F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SetupHomeBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupHomeLabel = lv_label_create(ui_Setup);
    lv_obj_set_width(ui_SetupHomeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetupHomeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetupHomeLabel, -30);
    lv_obj_set_y(ui_SetupHomeLabel, -14);
    lv_obj_set_align(ui_SetupHomeLabel, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_SetupHomeLabel, "Home");
    lv_obj_set_style_text_color(ui_SetupHomeLabel, lv_color_hex(0xFFE300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetupHomeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_TempCorrectionSlider, ui_event_TempCorrectionSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempSwingSlider, ui_event_TempSwingSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetupUncommonBtn, ui_event_SetupUncommonBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SetupHomeBtn, ui_event_SetupHomeBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Setup, ui_event_Setup, LV_EVENT_ALL, NULL);

}
