// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Thermostat

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_Screen1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xB787E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0xBE5757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 3);
    lv_obj_set_y(ui_Time, 3);
    lv_label_set_long_mode(ui_Time, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Time, "23:55:12");
    lv_obj_clear_flag(ui_Time, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Time, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 2);
    lv_obj_set_y(ui_Label1, -6);
    lv_obj_set_align(ui_Label1, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_long_mode(ui_Label1, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Label1, "Current:");
    lv_obj_clear_flag(ui_Label1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Label1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp, -33);
    lv_obj_set_y(ui_Temp, 103);
    lv_obj_set_align(ui_Temp, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Temp, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Temp, "72 ");
    lv_obj_set_style_text_align(ui_Temp, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, 21);
    lv_obj_set_y(ui_Humidity, 103);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Humidity, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Humidity, "62%");
    lv_obj_set_style_text_align(ui_Humidity, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Humidity, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ModeDropdown = lv_dropdown_create(ui_Screen1);
    lv_dropdown_set_options(ui_ModeDropdown, "Off\nIdle\nAuto\nHeat\nCool\nFan");
    lv_obj_set_width(ui_ModeDropdown, 99);
    lv_obj_set_height(ui_ModeDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ModeDropdown, 109);
    lv_obj_set_y(ui_ModeDropdown, -101);
    lv_obj_set_align(ui_ModeDropdown, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ModeDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ConfigButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_ConfigButton, 67);
    lv_obj_set_height(ui_ConfigButton, 30);
    lv_obj_set_x(ui_ConfigButton, -1);
    lv_obj_set_y(ui_ConfigButton, -1);
    lv_obj_set_align(ui_ConfigButton, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_ConfigButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ConfigButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_ConfigButton, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_ConfigButton, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConfigButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ConfigButton, lv_color_hex(0x2620F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ConfigButton, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetupBtn = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SetupBtn, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetupBtn, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetupBtn, -12);
    lv_obj_set_y(ui_SetupBtn, -8);
    lv_obj_set_align(ui_SetupBtn, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_long_mode(ui_SetupBtn, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_SetupBtn, "Setup");
    lv_obj_add_flag(ui_SetupBtn, LV_OBJ_FLAG_IGNORE_LAYOUT);     /// Flags
    lv_obj_clear_flag(ui_SetupBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scrollbar_mode(ui_SetupBtn, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_SetupBtn, lv_color_hex(0xFFE300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetupBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_Screen1);
    lv_obj_set_width(ui_Arc2, 150);
    lv_obj_set_height(ui_Arc2, 150);
    lv_obj_set_x(ui_Arc2, -66);
    lv_obj_set_y(ui_Arc2, 10);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_arc_set_range(ui_Arc2, 45, 92);
    lv_arc_set_value(ui_Arc2, 70);

    ui_SetTemp = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_SetTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTemp, -66);
    lv_obj_set_y(ui_SetTemp, -8);
    lv_obj_set_align(ui_SetTemp, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_SetTemp, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_SetTemp, "82°");
    lv_obj_clear_flag(ui_SetTemp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                      LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_SetTemp, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_font(ui_SetTemp, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 42);
    lv_obj_set_height(ui_Panel1, 34);
    lv_obj_set_x(ui_Panel1, 27);
    lv_obj_set_y(ui_Panel1, 61);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Panel1, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 27);
    lv_obj_set_y(ui_Label4, 57);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label4, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Label4, "-");
    lv_obj_set_style_text_font(ui_Label4, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 34);
    lv_obj_set_height(ui_Panel2, 34);
    lv_obj_set_x(ui_Panel2, 27);
    lv_obj_set_y(ui_Panel2, -49);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_blend_mode(ui_Panel2, LV_BLEND_MODE_MULTIPLY, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 28);
    lv_obj_set_y(ui_Label3, -49);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label3, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_Label3, "+");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Time, ui_event_Time, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label1, ui_event_Label1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Temp, ui_event_Temp, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Humidity, ui_event_Humidity, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ModeDropdown, ui_event_ModeDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc2, ui_event_Arc2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel1, ui_event_Panel1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Panel2, ui_event_Panel2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
