// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Thermostat

#include "../ui.h"

void ui_ThermostatRestart_screen_init(void)
{
ui_ThermostatRestart = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ThermostatRestart, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scrollbar_mode(ui_ThermostatRestart, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_bg_color(ui_ThermostatRestart, lv_color_hex(0xB787E2), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ThermostatRestart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_ThermostatRestart, lv_color_hex(0xBE5757), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_ThermostatRestart, LV_GRAD_DIR_HOR, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Notification = lv_label_create(ui_ThermostatRestart);
lv_obj_set_width( ui_Notification, lv_pct(70));
lv_obj_set_height( ui_Notification, lv_pct(13));
lv_obj_set_align( ui_Notification, LV_ALIGN_CENTER );
lv_label_set_text(ui_Notification,"Restarting Thermostat");
lv_obj_set_style_text_align(ui_Notification, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_Notification, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Notification, lv_color_hex(0xFFD800), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Notification, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Notification, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Notification, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Notification, 7, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Notification, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RestartCountdown = lv_label_create(ui_ThermostatRestart);
lv_obj_set_width( ui_RestartCountdown, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RestartCountdown, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_RestartCountdown, 52 );
lv_obj_set_x( ui_RestartCountdown, lv_pct(0) );
lv_obj_set_align( ui_RestartCountdown, LV_ALIGN_CENTER );
lv_label_set_text(ui_RestartCountdown,"30");
lv_obj_set_style_text_font(ui_RestartCountdown, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ThermostatRestart, ui_event_ThermostatRestart, LV_EVENT_ALL, NULL);

}
