// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Thermostat

#include "../ui.h"

void ui_WifiConfig_screen_init(void)
{
    ui_WifiConfig = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WifiConfig, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_WifiConfig, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_bg_color(ui_WifiConfig, lv_color_hex(0xB787E2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiConfig, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_WifiConfig, lv_color_hex(0xBE5757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_WifiConfig, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_WifiConfig);
    lv_obj_set_width(ui_Keyboard, 320);
    lv_obj_set_height(ui_Keyboard, 120);
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 60);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_Keyboard, lv_color_hex(0xBD6994), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Keyboard, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PSK = lv_textarea_create(ui_WifiConfig);
    lv_obj_set_width(ui_PSK, 205);
    lv_obj_set_height(ui_PSK, LV_SIZE_CONTENT);    /// 33
    lv_obj_set_x(ui_PSK, -55);
    lv_obj_set_y(ui_PSK, -21);
    lv_obj_set_align(ui_PSK, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_PSK, "Placeholder...");
    lv_textarea_set_one_line(ui_PSK, true);
    lv_obj_set_style_text_font(ui_PSK, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PwdLabel = lv_label_create(ui_WifiConfig);
    lv_obj_set_width(ui_PwdLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PwdLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PwdLabel, 6);
    lv_obj_set_y(ui_PwdLabel, -51);
    lv_obj_set_align(ui_PwdLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PwdLabel, "Password:");

    ui_SsidDropdown = lv_dropdown_create(ui_WifiConfig);
    lv_dropdown_set_options(ui_SsidDropdown, "");
    lv_obj_set_width(ui_SsidDropdown, 165);
    lv_obj_set_height(ui_SsidDropdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SsidDropdown, -1);
    lv_obj_set_y(ui_SsidDropdown, 1);
    lv_obj_set_align(ui_SsidDropdown, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_SsidDropdown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_ScanBtn = lv_btn_create(ui_WifiConfig);
    lv_obj_set_width(ui_ScanBtn, 100);
    lv_obj_set_height(ui_ScanBtn, 36);
    lv_obj_set_x(ui_ScanBtn, 1);
    lv_obj_set_y(ui_ScanBtn, 1);
    lv_obj_add_flag(ui_ScanBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScanBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScanBtn, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScanBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_ScanBtn, lv_color_hex(0x2620F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_ScanBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ScanLabel = lv_label_create(ui_WifiConfig);
    lv_obj_set_width(ui_ScanLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ScanLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ScanLabel, -111);
    lv_obj_set_y(ui_ScanLabel, -102);
    lv_obj_set_align(ui_ScanLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ScanLabel, "Scan");
    lv_obj_set_style_text_color(ui_ScanLabel, lv_color_hex(0xFFE300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ScanLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveBtn = lv_btn_create(ui_WifiConfig);
    lv_obj_set_width(ui_SaveBtn, 100);
    lv_obj_set_height(ui_SaveBtn, 36);
    lv_obj_set_x(ui_SaveBtn, -1);
    lv_obj_set_y(ui_SaveBtn, -20);
    lv_obj_set_align(ui_SaveBtn, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_SaveBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SaveBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SaveBtn, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SaveBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_SaveBtn, lv_color_hex(0x2620F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_SaveBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SaveLabel = lv_label_create(ui_WifiConfig);
    lv_obj_set_width(ui_SaveLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SaveLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SaveLabel, 109);
    lv_obj_set_y(ui_SaveLabel, -20);
    lv_obj_set_align(ui_SaveLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SaveLabel, "Save");
    lv_obj_set_style_text_color(ui_SaveLabel, lv_color_hex(0xFFE300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SaveLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelBtn = lv_btn_create(ui_WifiConfig);
    lv_obj_set_width(ui_CancelBtn, 100);
    lv_obj_set_height(ui_CancelBtn, 36);
    lv_obj_set_x(ui_CancelBtn, -1);
    lv_obj_set_y(ui_CancelBtn, -60);
    lv_obj_set_align(ui_CancelBtn, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_CancelBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CancelBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_CancelBtn, lv_color_hex(0x2095F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelBtn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_CancelBtn, lv_color_hex(0x2620F6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_CancelBtn, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelLabel = lv_label_create(ui_WifiConfig);
    lv_obj_set_width(ui_CancelLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CancelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CancelLabel, 109);
    lv_obj_set_y(ui_CancelLabel, -60);
    lv_obj_set_align(ui_CancelLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CancelLabel, "Cancel");
    lv_obj_set_style_text_color(ui_CancelLabel, lv_color_hex(0xFFE300), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CancelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiStatusLabel = lv_label_create(ui_WifiConfig);
    lv_obj_set_width(ui_WifiStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiStatusLabel, 6);
    lv_obj_set_y(ui_WifiStatusLabel, 42);
    lv_label_set_long_mode(ui_WifiStatusLabel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_WifiStatusLabel, "");
    lv_obj_clear_flag(ui_WifiStatusLabel,
                      LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_WifiStatusLabel, LV_SCROLLBAR_MODE_OFF);

    lv_keyboard_set_textarea(ui_Keyboard, ui_PSK);
    lv_obj_add_event_cb(ui_SsidDropdown, ui_event_SsidDropdown, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ScanBtn, ui_event_ScanBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveBtn, ui_event_SaveBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_CancelBtn, ui_event_CancelBtn, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiStatusLabel, ui_event_WifiStatusLabel, LV_EVENT_ALL, NULL);

}
