// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Thermostat

#ifndef _THERMOSTAT_UI_H
#define _THERMOSTAT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
void ui_event_MainScreen(lv_event_t * e);
extern lv_obj_t * ui_MainScreen;
void ui_event_TimeLabel(lv_event_t * e);
extern lv_obj_t * ui_TimeLabel;
void ui_event_StatusLabel(lv_event_t * e);
extern lv_obj_t * ui_StatusLabel;
void ui_event_TempLabel(lv_event_t * e);
extern lv_obj_t * ui_TempLabel;
void ui_event_HumidityLabel(lv_event_t * e);
extern lv_obj_t * ui_HumidityLabel;
void ui_event_ModeDropdown(lv_event_t * e);
extern lv_obj_t * ui_ModeDropdown;
void ui_event_SetupBtn(lv_event_t * e);
extern lv_obj_t * ui_SetupBtn;
extern lv_obj_t * ui_SetupLabel;
extern lv_obj_t * ui_SetTempBg1;
extern lv_obj_t * ui_SetTempBg;
void ui_event_TempArc(lv_event_t * e);
extern lv_obj_t * ui_TempArc;
void ui_event_SetTemp(lv_event_t * e);
extern lv_obj_t * ui_SetTemp;
extern lv_obj_t * ui_SetTempFrac;
void ui_event_TempDecreaseBtn(lv_event_t * e);
extern lv_obj_t * ui_TempDecreaseBtn;
extern lv_obj_t * ui_TempDecreaseLabel;
void ui_event_TempIncreaseBtn(lv_event_t * e);
extern lv_obj_t * ui_TempIncreaseBtn;
extern lv_obj_t * ui_TempIncreaseLabel;
void ui_event_InfoBtn(lv_event_t * e);
extern lv_obj_t * ui_InfoBtn;
extern lv_obj_t * ui_InfoLabel;
extern lv_obj_t * ui_WifiIndicatorLabel;
// SCREEN: ui_Info
void ui_Info_screen_init(void);
void ui_event_Info(lv_event_t * e);
extern lv_obj_t * ui_Info;
extern lv_obj_t * ui_WifiConnectedLabel;
extern lv_obj_t * ui_WifiConnCheckBox;
extern lv_obj_t * ui_WifiSsidLabel;
extern lv_obj_t * ui_IPLabel;
extern lv_obj_t * ui_HostnameLabel;
extern lv_obj_t * ui_RssiLabel;
extern lv_obj_t * ui_FwVersionLabel;
extern lv_obj_t * ui_BuildDateLabel;
extern lv_obj_t * ui_CopyrightLabel;
void ui_event_HomeBtn(lv_event_t * e);
extern lv_obj_t * ui_HomeBtn;
extern lv_obj_t * ui_HomeLabel;
// SCREEN: ui_Setup
void ui_Setup_screen_init(void);
void ui_event_Setup(lv_event_t * e);
extern lv_obj_t * ui_Setup;
extern lv_obj_t * ui_TempUnitsLabel;
extern lv_obj_t * ui_FahrenheitLabel;
extern lv_obj_t * ui_TempUnitsSwitch;
extern lv_obj_t * ui_CelciusLabel;
extern lv_obj_t * ui_TempCorrectionTextLabel;
extern lv_obj_t * ui_TempCorrectionLabel;
void ui_event_TempCorrectionSlider(lv_event_t * e);
extern lv_obj_t * ui_TempCorrectionSlider;
extern lv_obj_t * ui_TempSwingTextLabel;
extern lv_obj_t * ui_TempSwingLabel;
void ui_event_TempSwingSlider(lv_event_t * e);
extern lv_obj_t * ui_TempSwingSlider;
extern lv_obj_t * ui_HvacCoolLabel;
extern lv_obj_t * ui_HvacCoolCheckbox;
extern lv_obj_t * ui_HvacFanLabel;
extern lv_obj_t * ui_HvacFanCheckbox;
extern lv_obj_t * ui_RevValveLabel;
extern lv_obj_t * ui_DisabledCheckbox3;
void ui_event_SetupUncommonBtn(lv_event_t * e);
extern lv_obj_t * ui_SetupUncommonBtn;
extern lv_obj_t * ui_SetupUncommonLabel;
void ui_event_SetupHomeBtn(lv_event_t * e);
extern lv_obj_t * ui_SetupHomeBtn;
extern lv_obj_t * ui_SetupHomeLabel;
// SCREEN: ui_LessCommonSetup
void ui_LessCommonSetup_screen_init(void);
void ui_event_LessCommonSetup(lv_event_t * e);
extern lv_obj_t * ui_LessCommonSetup;
extern lv_obj_t * ui_TimezoneLabel1;
extern lv_obj_t * ui_TimezoneDropdown;
extern lv_obj_t * ui_UiSleepTextLabel;
extern lv_obj_t * ui_UiSleepLabel;
void ui_event_UiSleepSlider(lv_event_t * e);
extern lv_obj_t * ui_UiSleepSlider;
extern lv_obj_t * ui_DualStageHeatLabel;
extern lv_obj_t * ui_Hvac2StageHeatCheckbox;
extern lv_obj_t * ui_DisableLabel1;
extern lv_obj_t * ui_RevValveCheckbox;
extern lv_obj_t * ui_DisableLabel2;
extern lv_obj_t * ui_AudibleBeepCheckbox;
void ui_event_SetupWifiBtn1(lv_event_t * e);
extern lv_obj_t * ui_SetupWifiBtn1;
extern lv_obj_t * ui_SetupWifiLabel1;
void ui_event_SetupHomeBtn1(lv_event_t * e);
extern lv_obj_t * ui_SetupHomeBtn1;
extern lv_obj_t * ui_SetupHomeLabel1;
// SCREEN: ui_WifiConfig
void ui_WifiConfig_screen_init(void);
extern lv_obj_t * ui_WifiConfig;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_PSK;
extern lv_obj_t * ui_PwdLabel;
void ui_event_SsidDropdown(lv_event_t * e);
extern lv_obj_t * ui_SsidDropdown;
void ui_event_ScanBtn(lv_event_t * e);
extern lv_obj_t * ui_ScanBtn;
extern lv_obj_t * ui_ScanLabel;
void ui_event_SaveBtn(lv_event_t * e);
extern lv_obj_t * ui_SaveBtn;
extern lv_obj_t * ui_SaveLabel;
void ui_event_CancelBtn(lv_event_t * e);
extern lv_obj_t * ui_CancelBtn;
extern lv_obj_t * ui_CancelLabel;
void ui_event_WifiStatusLabel(lv_event_t * e);
extern lv_obj_t * ui_WifiStatusLabel;
extern lv_obj_t * ui____initial_actions0;

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
