// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: Thermostat

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void tftAwaken(lv_event_t * e);
void tftHvacModeChange(lv_event_t * e);
void tftBeep(lv_event_t * e);
void tftStopTouchTimer(lv_event_t * e);
void tftUpdateTempSet(lv_event_t * e);
void tftDecreaseSetTemp(lv_event_t * e);
void tftIncreaseSetTemp(lv_event_t * e);
void LoadInfoStrings(lv_event_t * e);
void LoadConfigSettings(lv_event_t * e);
void tftUpdateTempCorrectionValue(lv_event_t * e);
void tftUpdateTempSwingValue(lv_event_t * e);
void loadMqttSettings(lv_event_t * e);
void LoadUncommonSettings(lv_event_t * e);
void SaveConfigSettings(lv_event_t * e);
void tftCalibrate(lv_event_t * e);
void tftUpdateUiSleepValue(lv_event_t * e);
void tftClearPsk(lv_event_t * e);
void SaveUncommonConfigSettings(lv_event_t * e);
void StartWifiScan(lv_event_t * e);
void tftSetNewWifi(lv_event_t * e);
void stopWifiScan(lv_event_t * e);
void ShowQrOnScreen(lv_event_t * e);
void tftCountdown(lv_event_t * e);
void saveMqttSettings(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
