// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Thermostat

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void tftAwaken(lv_event_t * e);
void tftAwaken(lv_event_t * e);
void tftAwaken(lv_event_t * e);
void tftAwaken(lv_event_t * e);
void tftAwaken(lv_event_t * e);
void tftHvacModeChange(lv_event_t * e);
void tftStopTouchTimer(lv_event_t * e);
void tftUpdateTempSet(lv_event_t * e);
void tftAwaken(lv_event_t * e);
void tftUpdateTempSet(lv_event_t * e);
void tftAwaken(lv_event_t * e);
void tftAwaken(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
