// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: Thermostat

#include "thermostat.hpp"
#include "ui.h"

void tftUpdateTempSet(lv_event_t * e)
{
  char tmp[16];
  strncpy(tmp, lv_label_get_text(ui_SetTemp), sizeof(tmp));
  OperatingParameters.tempSet = atoi(tmp);
  tftWakeDisplay();
}

void tftHvacModeChange(lv_event_t * e)
{
  OperatingParameters.hvacSetMode = lv_dropdown_get_selected(ui_ModeDropdown);
  tftWakeDisplay();
}

void tftAwaken(lv_event_t * e)
{
  tftWakeDisplay();
}

void tftStopTouchTimer(lv_event_t * e)
{
  tftDisableTouchTimer();
}
