name: CI

on:
  push:
    tags:
      - 'v*' # Triggers on semantic version tags like v1.0.0, v2.1, etc.
    #  *      # OR use '*' if you want it to trigger on ANY tag name
  workflow_dispatch:
#  release:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build
        run: pio run -d app/

      - uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: |
            .pio/build/esp32s3/firmware.bin
            .pio/build/esp32s3/firmware.elf
          if-no-files-found: error

      # Changed github.event.release.tag_name to github.ref_name
      - name: Add firmware.bin to release
        run: gh release upload ${{ github.ref_name }} app/.pio/build/esp32s3/firmware.bin
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}

      # Changed github.event.release.tag_name to github.ref_name
      - name: Add firmware.elf to release
        run: gh release upload ${{ github.ref_name }} app/.pio/build/esp32s3/firmware.elf
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
